// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYdM5-wuNYJa9OU1Kw6i7lqJNWzi77-Bk',
    appId: '1:703883453569:web:5e3d35297a0eada4d65980',
    messagingSenderId: '703883453569',
    projectId: 'homio-2fade',
    authDomain: 'homio-2fade.firebaseapp.com',
    storageBucket: 'homio-2fade.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5L9ALeFkOUWhS8_ZqFa8j1lVDUg0LjM',
    appId: '1:703883453569:android:020f9ce8c92a374ad65980',
    messagingSenderId: '703883453569',
    projectId: 'homio-2fade',
    storageBucket: 'homio-2fade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx13BcE_CKAp1evu2N67JzPm2ObD6TDhE',
    appId: '1:703883453569:ios:89a51435213f496cd65980',
    messagingSenderId: '703883453569',
    projectId: 'homio-2fade',
    storageBucket: 'homio-2fade.firebasestorage.app',
    iosBundleId: 'com.rental.ite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx13BcE_CKAp1evu2N67JzPm2ObD6TDhE',
    appId: '1:703883453569:ios:89a51435213f496cd65980',
    messagingSenderId: '703883453569',
    projectId: 'homio-2fade',
    storageBucket: 'homio-2fade.firebasestorage.app',
    iosBundleId: 'com.rental.ite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYdM5-wuNYJa9OU1Kw6i7lqJNWzi77-Bk',
    appId: '1:703883453569:web:021b7d3fbe72b05fd65980',
    messagingSenderId: '703883453569',
    projectId: 'homio-2fade',
    authDomain: 'homio-2fade.firebaseapp.com',
    storageBucket: 'homio-2fade.firebasestorage.app',
  );
}
